crop:
  x_load_path: ???
  y_load_path: ???
  para_load_path: ???
  y_save_fold: ???
  result_save_fold: ???
  frame: [0, -1]
  chunk_size: 32
  # true: stitched seam-aware patching; 
  # false: regular tile grid patching
  after_stitch: true
  # seam
  seam_width: 4
  tile_size: 500
  # seam filter
  coverage_ratio: 0.5
  min_patch_size: 40
  # patch
  pad: 20
