# @package _global_

defaults:
  - /schema/normalize@_here_
  - /schema/stitch@_here_
  - /schema/crop@_here_
  - /schema/extract@_here_
  - /schema/save@_here_
  - _self_

enable: true
x_path: ???
y_path: null              # default: dirname(x_load_path)/Y.tif
chunk_size: 16

normalize:
  enable: ${enable}
  x_load_path: ${x_path}
  x_save_path: ${x_path}
  chunk_size: ${chunk_size}

stitch:
  enable: ${enable}
  x_load_path: ${x_path}
  y_save_path: ${y_path}
  stitch_save_fold: null  # default: dirname(y_save_path)/stitch/
  chunk_size: ${chunk_size}

crop:
  enable: ${enable}
  x_load_path: ${x_path}
  y_load_path: ${y_path}
  stitch_load_fold: ${stitch.stitch_save_fold}
  y_save_fold: null       # default: stem(y_load_path)
  crop_save_fold: null    # default: dirname(y_save_path)/crop/
  chunk_size: ${chunk_size}

extract:
  enable: ${enable}
  y_load_fold: ${crop.y_save_fold}
  extract_save_fold: null # default: dirname(y_load_fold)/extract/

save:
  enable: ${enable}
  x_load_path: ${x_path}
  y_load_path: ${y_path}
  crop_load_path: ${crop.crop_save_fold}
  extract_fold: ${extract.extract_save_fold}
  save_fold: null         # default: dirname(y_load_fold)/save/
